apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    cert-manager.io/cluster-issuer: "pi-cluster-ca-issuer"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # Rewrite /grafana to / for Grafana
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "pi-k3s.local"
        - "192-168-1-55.sslip.io"
      secretName: grafana-tls
  rules:
    # sslip.io provides wildcard DNS: 192-168-1-55.sslip.io -> 192.168.1.55
    - host: "192-168-1-55.sslip.io"
      http:
        paths:
          - path: /grafana(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: kube-prometheus-grafana
                port:
                  number: 3000
    # Also support local hostname
    - host: "pi-k3s.local"
      http:
        paths:
          - path: /grafana(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: kube-prometheus-grafana
                port:
                  number: 3000
