apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Don't override namespace - resources have explicit namespaces
resources:
  - external-secret.yaml
  - helmrelease.yaml
  - dashboard-pihole.yaml
  - dashboard-k8s-overview.yaml
