apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: carl
  namespace: carl
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - carl.lab.mtgibbs.dev
      secretName: carl-tls
  rules:
    - host: carl.lab.mtgibbs.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: carl
                port:
                  number: 8080
