apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
  annotations:
    cert-manager.io/cluster-issuer: "pi-cluster-ca-issuer"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # Rewrite /status to / for Uptime Kuma
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "pi-k3s.local"
        - "192-168-1-55.sslip.io"
      secretName: uptime-kuma-tls
  rules:
    - host: "192-168-1-55.sslip.io"
      http:
        paths:
          - path: /status(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: uptime-kuma
                port:
                  number: 3001
    - host: "pi-k3s.local"
      http:
        paths:
          - path: /status(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: uptime-kuma
                port:
                  number: 3001
