apiVersion: v1
kind: Service
metadata:
  name: mtgibbs-site
  namespace: mtgibbs-site
spec:
  selector:
    app: mtgibbs-site
  ports:
    - port: 3000
      targetPort: 3000
      name: http
  type: ClusterIP
