apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backup-jobs
resources:
  - namespace.yaml
  - external-secret.yaml
  - backup-cronjob.yaml
  - postgres-backup-secret.yaml
  - postgres-backup-cronjob.yaml
  - media-backup-cronjob.yaml
