apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: deployments
  namespace: flux-system
spec:
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: '*'
    - kind: HelmRelease
      name: '*'
    - kind: HelmRelease
      name: '*'
      namespace: immich
    - kind: HelmRelease
      name: '*'
      namespace: monitoring
  exclusionList:
    # Filter out noisy transient messages
    - ".*waiting.*socket.*"
    - ".*Dependencies do not meet ready condition.*"
    - ".*HelmChart.*is not ready.*"
