apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Don't override namespace - resources have explicit namespaces
resources:
  - namespace.yaml
  - external-secret.yaml
  - nfs-pv.yaml
  - library-pvc.yaml
  - helmrelease.yaml
